sudo: required
language: generic

services:
  - docker

before_install:

  - docker build -t colteks01/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true colteks01/react-test npm test

  - docker build -t colteks/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true colteks/react-test npm test

after_success:
  - docker build -t colteks01/multi-client ./client
  - docker build -t colteks01/multi-nginx ./nginx
  - docker build -t colteks01/multi-server ./server
  - docker build -t colteks01/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push colteks01/multi-client
  - docker push colteks01/multi-nginx
  - docker push colteks01/multi-server
  - docker push colteks01/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-west-1-684268413554'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
